# Generated by Django 5.2.4 on 2025-07-20 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Constructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('base', models.CharField(max_length=100)),
                ('championships', models.IntegerField(default=0)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='constructors/')),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('driver_number', models.PositiveIntegerField()),
                ('country', models.CharField(max_length=100)),
                ('driver_photo', models.ImageField(blank=True, null=True, upload_to='drivers/photos/')),
                ('car_photo', models.ImageField(blank=True, null=True, upload_to='drivers/cars/')),
                ('country_flag', models.ImageField(blank=True, null=True, upload_to='drivers/flags/')),
                ('career_points', models.FloatField(default=0)),
                ('highest_race_finish', models.CharField(blank=True, max_length=20)),
                ('podiums', models.IntegerField(default=0)),
                ('world_championships', models.IntegerField(default=0)),
                ('dnfs', models.IntegerField(default=0)),
                ('date_of_birth', models.DateField()),
                ('place_of_birth', models.CharField(max_length=100)),
                ('constructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drivers', to='f1app.constructor')),
            ],
        ),
    ]
